#!/usr/bin/env node
// Build browser assets from the canonical question bank.

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const SOURCE = path.join(ROOT, "question_bank.json");
const DATA_JS = path.join(ROOT, "assets", "data.js");
const SCORES_JS = path.join(ROOT, "assets", "final_scores.js");

function uniqueChapters(questions, subject) {
  const seen = new Set();
  const chapters = [];
  for (const q of questions) {
    if (q.subject !== subject || seen.has(q.chapter)) continue;
    seen.add(q.chapter);
    chapters.push(q.chapter);
  }
  return chapters;
}

function bankRefsOf(q) {
  return (q.bankRef || "").match(/Q[12]\.\d+/g) || [];
}

function validate(bank) {
  if (!Array.isArray(bank.questions)) throw new Error("question_bank.json: questions must be an array");
  if (!Array.isArray(bank.finalScores)) throw new Error("question_bank.json: finalScores must be an array");

  const ids = new Set();
  for (const q of bank.questions) {
    if (!q.id) throw new Error("question without id");
    if (ids.has(q.id)) throw new Error(`duplicate question id: ${q.id}`);
    ids.add(q.id);
  }

  const represented = new Set();
  for (const q of bank.questions) {
    for (const ref of bankRefsOf(q)) represented.add(ref);
  }

  const missing = bank.finalScores
    .filter(row => /^[ABC]/.test(row.tier))
    .map(row => row.qid)
    .filter(qid => !represented.has(qid));

  if (missing.length) {
    throw new Error(`A/B/C score rows missing question cards: ${missing.join(", ")}`);
  }
}

function main() {
  const bank = JSON.parse(fs.readFileSync(SOURCE, "utf8"));
  validate(bank);

  const questions = bank.questions;
  const data = {
    meta: {
      ...(bank.meta || {}),
      extractedAt: new Date().toISOString(),
      totalQuestions: questions.length,
      measureChapters: uniqueChapters(questions, "measure"),
      functionalChapters: uniqueChapters(questions, "functional")
    },
    finalScores: bank.finalScores,
    questions
  };

  fs.writeFileSync(
    DATA_JS,
    `// Auto-generated by build_question_data.js — do not edit manually\n`
      + `// Source: question_bank.json\n`
      + `// Generated: ${new Date().toISOString()}\n`
      + `window.RFA_DATA = ${JSON.stringify(data, null, 2)};\n`,
    "utf8"
  );

  fs.writeFileSync(
    SCORES_JS,
    `// Auto-generated by build_question_data.js — do not edit manually\n`
      + `// Source: question_bank.json\n`
      + `window.RFA_FINAL_SCORES = ${JSON.stringify(bank.finalScores, null, 2)};\n`,
    "utf8"
  );

  console.log(`Wrote assets/data.js with ${questions.length} questions`);
  console.log(`Wrote assets/final_scores.js with ${bank.finalScores.length} scores`);
}

main();
